    
server:
  port: 8083
spring:
#  datasource:
#     url: jdbc:mysql://localhost:3306/microservices
#     username: root
#     password: root
#     driver-class-name: com.mysql.cj.jdbc.Driver
     
  application:
    name: rating-service  
     
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
  config:
    import: configserver:http://localhost:8085 
  profiles:
    active: dev    

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka